name: CI

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Setup NodeJS Environment
        uses: actions/setup-node@v4
        with:
<<<<<<< HEAD
          node-version: 18
=======
          node-version: 20.x
>>>>>>> d05d313 (ci(github-actions): Setup Github Actions for the monorepo)
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
